### ISSUE TITLE
error while using recipe rayo in centos

### ISSUE THREAD

**Issue by timusg** [benlangfeld/freeswitch-cookbook#10]
rayo recipe install FS and other packages of version 1.2.17
but looks like freeswitch-config-rayo is not updated on centos repo.

Error: Package: freeswitch-config-rayo-1.2.16-1.el6.noarch (freeswitch)
           Requires: freeswitch = 1.2.16
           Installed: freeswitch-1.2.17-1.el6.x86_64 (@ freeswitch)
               freeswitch = 1.2.17-1.el6

**Comment by benlangfeld** [comment]
I already opened a JIRA for this

**Comment by timusg** [comment]
@bklang thanks for information, 
also attaching JIRA url for further tracking in this issue.

url:
http://jira.freeswitch.org/browse/FS-6162

**Comment by benlangfeld** [comment]
I'm not @bklang, but yep :)
