### ISSUE TITLE
Doing a source install of rayo results in no rayo.conf being created

### ISSUE THREAD

**Issue by JustinAiken** [benlangfeld/freeswitch-cookbook#9]
With these attributes: 

``` ruby
      chef.json = {
        freeswitch: {
          install_method: "source",
          source: {
            git_branch: "master",
          },
          local_ip: public_ip,
          domain: domain
        }
      }
```

Running the `freeswitch::rayo` recipe leaves you with no `rayo.conf` being created at all.

**Comment by benlangfeld** [comment]
Could you provide debug logs of the chef run?

**Comment by JustinAiken** [comment]
https://gist.github.com/JustinAiken/7763ee3bca4b25c893dc

**Comment by benlangfeld** [comment]
This was fixed in https://github.com/mojolingo/freeswitch-cookbook/commit/4b47d5865e69fe0d21c0735574896d1fac9cf375 and will be in 0.3.1 shortly.

**Comment by JustinAiken** [comment]
Sweet, thanks!

**Comment by benlangfeld** [comment]
0.3.1 is out.
